// W5 SG PoC (v3 pre-research): [GlobalClass] assembly-level registry generator.
//
// For every user class marked [GlobalClass] this generator emits ONE file per
// compilation containing a module initializer that pushes the registry into
// the engine at assembly-load time:
//
//   Godot.ScriptRegistry.RegisterGlobalClass("Player", "CharacterBody2D", 0, 0, null);
//
// The engine triggers it via mono_runtime_class_init(<Module>) from
// CSharpLanguage::refresh_global_classes() (eval §5.3 方式 A). The generated
// code carries its own netstandard2.0 ModuleInitializerAttribute polyfill
// (the real attribute is net5+ only; Roslyn resolves the initializer by full
// type name, so an internal polyfill works).
//
// Design note (migration cost finding recorded in
// docs/poc_2026-08-18_v3_sourcegenerators.md): this registry approach does
// NOT emit partial-class extensions, so user classes do NOT need the
// `partial` modifier — the eval §2.1 "must be partial" constraint applies
// only to the later per-class __Register method design (eval §2.4).

using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GodotSharp.SourceGenerators
{
    [Generator]
    public sealed class GlobalClassGenerator : IIncrementalGenerator
    {
        private const string GlobalClassAttributeFullName = "Godot.GlobalClassAttribute";
        private const string ToolAttributeFullName = "Godot.ToolAttribute";

        private readonly record struct GlobalClassEntry(
            string ClassName,
            string BaseTypeName,
            bool IsTool,
            bool IsAbstract,
            string IconPath);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entries = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    GlobalClassAttributeFullName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, ct) => Transform(ctx, ct))
                .Where(static e => e is not null)
                .Select(static (e, _) => e!.Value)
                .Collect();

            context.RegisterImplementationSourceOutput(entries, static (spc, entries) =>
                Emit(spc, entries));
        }

        private static GlobalClassEntry? Transform(GeneratorAttributeSyntaxContext ctx, System.Threading.CancellationToken ct)
        {
            ct.ThrowIfCancellationRequested();

            if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            {
                return null;
            }

            // Base type: simple name, matching the C++ typedef scan
            // (mono_class_get_name(mono_class_get_parent(klass))). Falls back
            // to "Node" on the C++ side when no base type is declared.
            string baseType = typeSymbol.BaseType?.Name ?? "";

            // [Tool] on the same class — merged into the same push call.
            bool isTool = typeSymbol.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == ToolAttributeFullName);

            // IconPath is a named property on GlobalClassAttribute.
            string iconPath = null;
            AttributeData attr = ctx.Attributes[0];
            foreach (KeyValuePair<string, TypedConstant> named in attr.NamedArguments)
            {
                if (named.Key == "IconPath" && named.Value.Value is string s)
                {
                    iconPath = s;
                }
            }

            return new GlobalClassEntry(
                typeSymbol.Name,
                baseType,
                isTool,
                typeSymbol.IsAbstract,
                iconPath);
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<GlobalClassEntry> entries)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by GodotSharp.SourceGenerators (W5 SG PoC).");
            sb.AppendLine("//   Runs once per assembly load (module initializer) and pushes the");
            sb.AppendLine("//   compile-time [GlobalClass] registry into the engine via icall,");
            sb.AppendLine("//   replacing the C++ TypeDef reflection scan for this assembly.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#pragma warning disable CS0436 // ModuleInitializerAttribute polyfill for netstandard2.0");
            sb.AppendLine();
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            sb.AppendLine("    [System.AttributeUsage(System.AttributeTargets.Method, AllowMultiple = false)]");
            sb.AppendLine("    internal sealed class ModuleInitializerAttribute : System.Attribute { }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("namespace Godot");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class __GlobalClassRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        [System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("        internal static void __Register()");
            sb.AppendLine("        {");

            foreach (GlobalClassEntry e in entries)
            {
                sb.Append("            ScriptRegistry.RegisterGlobalClass(")
                    .Append(Literal(e.ClassName)).Append(", ")
                    .Append(Literal(e.BaseTypeName)).Append(", ")
                    .Append(e.IsTool ? "1" : "0").Append(", ")
                    .Append(e.IsAbstract ? "1" : "0").Append(", ")
                    .Append(Literal(e.IconPath))
                    .AppendLine(");");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource(
                "GodotGlobalClassRegistry.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string Literal(string value)
        {
            if (value is null)
            {
                return "null";
            }
            // Escape for a C# string literal (backslash, quote, newline, CR).
            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    default: sb.Append(c); break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
    }
}
