<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>GodotSharp</AssemblyName>
    <RootNamespace>Godot</RootNamespace>
    <LangVersion>latest</LangVersion>
    <OutputPath>..\..\..\..\bin\GodotSharp\Api\Debug\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>portable</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
