#!/usr/bin/env python
from misc.utility.scons_hints import *

from platform_ios_builders import generate_bundle

from platform_methods import combine_libs_apple_embedded

Import("env")

ios_lib = [
    "device_metrics.mm",
    "display_layer_ios.mm",
    "display_server_ios.mm",
    "godot_view_ios.mm",
    "main_ios.mm",
    "os_ios.mm",
]

env_ios = env.Clone()
ios_lib = env_ios.add_library("ios", ios_lib)

# (iOS) Enable module support
env_ios.Append(CCFLAGS=["-fmodules", "-fcxx-modules"])

if "LIBS_EXTERNAL" in env_ios:
    env_ios.Depends(ios_lib, env_ios["LIBS_EXTERNAL"])

# Editor builds go to bin/<platform>/, export templates go to templates/<platform>/.
output_prefix = "#bin/ios" if env.editor_build else "#templates/ios"

combine_command = env_ios.CommandNoCache(
    output_prefix + "/libgodot" + env_ios["LIBSUFFIX"], [ios_lib] + env_ios["LIBS"], env.Run(combine_libs_apple_embedded)
)

if env["generate_bundle"]:
    env.AlwaysBuild(env.CommandNoCache("generate_bundle", combine_command, env.Run(generate_bundle)))
