#!/usr/bin/env python

Import("env")
Import("env_modules")

env_mono = env_modules.Clone()

mono_enabled = env.get("module_mono_new_enabled", True)
mono_static = env.get("mono_new_static", True)
mono_stub = env.get("mono_new_stub", False)
mono_prefix = env.get("mono_new_prefix", "")
mono_web = env.get("mono_new_web_support", False)

# For Web platform, check if WASM static libs exist; if not, fall back to stub
if env["platform"] == "web" and not mono_stub and not mono_prefix:
    import os
    _web_lib_path = env.Dir("#modules/mono_new/thirdparty/mono/wasm").abspath
    _main_lib = os.path.join(_web_lib_path, "libmini.a")
    if not os.path.isfile(_main_lib):
        mono_stub = True
        mono_static = False

if not mono_enabled:
    Return()

def get_platform_lib_subdir(env):
    plat = env["platform"]
    arch = env.get("arch", "x86_64")
    if plat == "windows":
        return "windows/" + arch
    elif plat == "macos":
        return "macos/" + arch
    elif plat == "web":
        return "../wasm"  # Use thirdparty/mono/wasm for WASM libs
    elif plat == "linuxbsd" or plat == "linux":
        return "linux/" + arch
    elif plat == "android":
        return "android/" + arch
    elif plat == "ios":
        return "ios/" + arch
    else:
        return plat + "/" + arch

if mono_prefix:
    mono_lib_path = mono_prefix + "/lib"
    mono_inc_path = mono_prefix + "/include/mono-2.0"
    mono_wasm_inc_path = None
else:
    if env["platform"] == "web":
        mono_lib_path = "#modules/mono_new/thirdparty/mono/wasm"
        mono_inc_path = "#modules/mono_new/thirdparty/mono/include/mono-2.0"
        mono_wasm_inc_path = "#modules/mono_new/thirdparty/mono/include/mono-2.0/wasm"
    else:
        mono_lib_base = "#modules/mono_new/thirdparty/mono/lib"
        mono_lib_platform = mono_lib_base + "/" + get_platform_lib_subdir(env)
        mono_inc_path = "#modules/mono_new/thirdparty/mono/include/mono-2.0"
        mono_wasm_inc_path = None

        import os
        _plat_path = env.Dir(mono_lib_platform).abspath
        if os.path.isdir(_plat_path):
            mono_lib_path = mono_lib_platform
        else:
            mono_lib_path = mono_lib_base

        system_mono_lib = "C:/Program Files/Mono/lib"
        if os.path.isdir(system_mono_lib) and not mono_stub:
            mono_lib_path = system_mono_lib

env_mono.add_source_files(env.modules_sources, "*.cpp")
env_mono.add_source_files(env.modules_sources, "mono_gd/*.cpp")
env_mono.add_source_files(env.modules_sources, "mono_gd/interop/*.cpp")
env_mono.add_source_files(env.modules_sources, "mono_runtime/*.cpp")
env_mono.add_source_files(env.modules_sources, "utils/*.cpp")
env_mono.add_source_files(env.modules_sources, "glue/*.cpp")
env_mono.add_source_files(env.modules_sources, "glue/glue_cpp/*.cpp")

if env["platform"] == "web":
    env_mono.add_source_files(env.modules_sources, "platform/mono_platform_web.cpp")
    env_mono.add_source_files(env.modules_sources, "platform/mini_wasm_stubs.c")

if env.editor_build:
    env_mono.add_source_files(env.modules_sources, "editor/*.cpp")

if mono_wasm_inc_path:
    env_mono.Append(CPPPATH=[mono_wasm_inc_path])
env_mono.Append(CPPPATH=[mono_inc_path])
env_mono.Append(CPPPATH=["#modules/mono_new/"])
env_mono.Append(CPPPATH=["#modules/mono_new/platform/"])

if mono_stub:
    env_mono.add_source_files(env.modules_sources, "thirdparty/mono/stub/*.cpp")
    env_mono.Append(CPPDEFINES=["MONO_STUB"])
    env_mono.Append(CPPDEFINES=["MONO_STATIC_BUILD"])
    env_mono.Append(CPPDEFINES=["MONO_STATIC"])
    if env["platform"] == "windows":
        if env.msvc:
            env.Append(LINKFLAGS=["psapi.lib", "ws2_32.lib", "winmm.lib", "version.lib", "iphlpapi.lib", "oleaut32.lib", "advapi32.lib", "user32.lib", "shell32.lib", "ole32.lib", "bcrypt.lib"])
        else:
            env.Append(LIBS=["psapi", "ws2_32", "winmm", "version", "iphlpapi", "oleaut32", "advapi32", "user32", "shell32", "ole32", "bcrypt"])
    elif env["platform"] == "web":
        env_mono.Append(CPPDEFINES=["MONO_Web"])
        env_mono.Append(CPPDEFINES=["DISABLE_THREADS"])
        env_mono.Append(CPPDEFINES=["UNIX_ENABLED"])
elif mono_static:
    if env["platform"] == "windows":
        if env.msvc:
            import os
            mono_lib_abs = os.path.join(env.Dir(mono_lib_path).abspath, "mono-2.0-sgen.lib")
            if not os.path.isfile(mono_lib_abs):
                mono_lib_abs = os.path.join(env.Dir("#").abspath, "modules", "mono_new", "thirdparty", "mono", "lib", "mono-2.0-sgen.lib")
            env.Append(LINKFLAGS=[mono_lib_abs, "psapi.lib", "ws2_32.lib", "winmm.lib", "version.lib", "iphlpapi.lib", "oleaut32.lib", "advapi32.lib", "user32.lib", "shell32.lib", "ole32.lib", "bcrypt.lib"])
        else:
            env.Append(LIBS=["mono-2.0-sgen", "psapi", "ws2_32", "winmm", "version", "iphlpapi", "oleaut32", "advapi32", "user32", "shell32", "ole32", "bcrypt"])
            env.Append(LIBPATH=[mono_lib_path])
    elif env["platform"] == "web":
        # Link Mono WASM static libraries.
        # Order matters for static linking; use --whole-archive to prevent
        # the linker from stripping symbols referenced only via function pointers.
        env.Append(LIBPATH=[mono_lib_path])
        env.Append(LINKFLAGS=["-Wl,--whole-archive"])
        # The core Mono libraries needed for interpreter mode (no JIT/AOT):
        # - monosgen-2.0: mini runtime (JIT compiler, codegen, trampolines, zlib)
        # - mono-ee-interp: the interpreter execution engine
        # - monoruntimesgen: runtime classes, metadata, SGen GC integration
        # - mono-ilgen: IL code generation for dynamic methods
        # - monoruntime-support: runtime support utilities
        # - eglib: embedded glib replacement
        # - mono-icall-table: internal call table
        # - monoutils: mono utilities (dlmalloc, codeman, etc.)
        # - mono-dbg: debugger support
        # - z: zlib compression
        # - monomath: math helpers
        # - monoruntime-config: runtime configuration
        env.Append(LIBS=[
            "monosgen-2.0",
            "mono-ee-interp",
            "monoruntimesgen",
            "mono-ilgen",
            "monoruntime-support",
            "eglib",
            "mono-icall-table",
            "monoutils",
            "mono-dbg",
            "z",
            "monomath",
            "monoruntime-config",
        ])
        env.Append(LINKFLAGS=["-Wl,--no-whole-archive"])
        env_mono.Append(CPPDEFINES=["MONO_Web"])
        env_mono.Append(CPPDEFINES=["DISABLE_THREADS"])
        env_mono.Append(CPPDEFINES=["HAVE_SGEN_GC"])
        # Emscripten linker flags for Mono WASM
        env.Append(LINKFLAGS=[
            "-s", "ALLOW_MEMORY_GROWTH=1",
            "-s", "EXPORTED_RUNTIME_METHODS=['ccall','cwrap','stringToUTF8','UTF8ToString','FS']",
            "-s", "ERROR_ON_UNDEFINED_SYMBOLS=0",
            "-s", "WARN_ON_UNDEFINED_SYMBOLS=0",
            "-O1",
            "--profiling-funcs",
        ])
        # Provide JS implementations of Mono WASM runtime functions
        # that Mono expects from the JavaScript environment.
        _wasm_runtime_js = os.path.join(env.Dir("#modules/mono_new/platform").abspath, "mono_wasm_runtime.js").replace("\\", "/")
        if os.path.isfile(_wasm_runtime_js):
            env.Append(LINKFLAGS=["--js-library", _wasm_runtime_js])
        # Embed BCL and C# assemblies into MEMFS via --preload-file.
        # Files under modules/mono_new/preload/ are mounted at / in the WASM
        # virtual filesystem so that Mono can find /mono/lib/mono/4.5/mscorlib.dll
        # and /.mono/assemblies/GodotSharp.dll at runtime.
        import os
        _preload_abs = env.Dir("#modules/mono_new/preload").abspath.replace("\\", "/")
        if os.path.isdir(_preload_abs) and os.listdir(_preload_abs):
            env.Append(LINKFLAGS=[
                "--preload-file",
                _preload_abs + "@/",
            ])
    elif env["platform"] == "macos":
        env.Append(LIBS=["mono-2.0-sgen", "pthread", "m", "dl"])
        env.Append(LIBPATH=[mono_lib_path])
        env.Append(LINKFLAGS=["-framework", "CoreFoundation", "-framework", "Foundation"])
    else:
        env.Append(LIBS=["mono-2.0-sgen", "pthread", "m", "dl", "rt"])
        env.Append(LIBPATH=[mono_lib_path])

    env_mono.Append(CPPDEFINES=["MONO_STATIC"])
    env_mono.Append(CPPDEFINES=["MONO_STATIC_BUILD"])
    env_mono.Append(CPPDEFINES=["MONO_PINVOKE_REDUCED"])
else:
    if env.msvc:
        env.Append(LIBS=["mono-2.0"])
        env.Append(LIBPATH=[mono_lib_path])

if env["platform"] == "web":
    env_mono.Append(CPPDEFINES=["WEB_ENABLED"])
    env_mono.Append(CPPDEFINES=["UNIX_ENABLED"])
    env_mono.Append(CPPDEFINES=["MONO_Web"])
    env_mono.Append(CPPDEFINES=["MONO_DLL_IMPORT="])
    if mono_web:
        env_mono.Append(CPPDEFINES=["MONO_WEB_FULL"])
