// AUTO-GENERATED by generate_glue.py - DO NOT EDIT BY HAND.
// Source spec: timer_glue.spec.json
//
// C# icall declarations and public wrapper methods for Timer.

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Godot
{
public partial class Timer
{
	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_SetWaitTime(long node, long p_time);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static long godot_icall_Timer_GetWaitTime(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_SetOneShot(long node, bool p_one_shot);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static bool godot_icall_Timer_IsOneShot(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_SetAutostart(long node, bool p_start);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static bool godot_icall_Timer_HasAutostart(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_Start(long node, long p_time);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_Stop(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_SetPaused(long node, bool p_paused);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static bool godot_icall_Timer_IsPaused(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static void godot_icall_Timer_SetIgnoreTimeScale(long node, bool p_ignore);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static bool godot_icall_Timer_IsIgnoringTimeScale(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static bool godot_icall_Timer_IsStopped(long node);

	[MethodImpl(MethodImplOptions.InternalCall)]
	internal extern static long godot_icall_Timer_GetTimeLeft(long node);

	public void SetWaitTime(double p_time)
	{
		long p_time_bits = new DoubleLongUnion { DoubleValue = p_time }.LongValue;
		godot_icall_Timer_SetWaitTime(nativeInstance, p_time_bits);
	}

	public double GetWaitTime()
	{
		return new DoubleLongUnion { LongValue = godot_icall_Timer_GetWaitTime(nativeInstance) }.DoubleValue;
	}

	public void SetOneShot(bool p_one_shot)
	{
		godot_icall_Timer_SetOneShot(nativeInstance, p_one_shot);
	}

	public bool IsOneShot()
	{
		return godot_icall_Timer_IsOneShot(nativeInstance);
	}

	public void SetAutostart(bool p_start)
	{
		godot_icall_Timer_SetAutostart(nativeInstance, p_start);
	}

	public bool HasAutostart()
	{
		return godot_icall_Timer_HasAutostart(nativeInstance);
	}

	public void Start(double p_time)
	{
		long p_time_bits = new DoubleLongUnion { DoubleValue = p_time }.LongValue;
		godot_icall_Timer_Start(nativeInstance, p_time_bits);
	}

	public void Stop()
	{
		godot_icall_Timer_Stop(nativeInstance);
	}

	public void SetPaused(bool p_paused)
	{
		godot_icall_Timer_SetPaused(nativeInstance, p_paused);
	}

	public bool IsPaused()
	{
		return godot_icall_Timer_IsPaused(nativeInstance);
	}

	public void SetIgnoreTimeScale(bool p_ignore)
	{
		godot_icall_Timer_SetIgnoreTimeScale(nativeInstance, p_ignore);
	}

	public bool IsIgnoringTimeScale()
	{
		return godot_icall_Timer_IsIgnoringTimeScale(nativeInstance);
	}

	public bool IsStopped()
	{
		return godot_icall_Timer_IsStopped(nativeInstance);
	}

	public double GetTimeLeft()
	{
		return new DoubleLongUnion { LongValue = godot_icall_Timer_GetTimeLeft(nativeInstance) }.DoubleValue;
	}
}
}
