// ICall bindings for Node
// Auto-generated by glue generator

#include "../../mono_gd/interop/gd_mono_interop_variant.h"

namespace GDMonoInterop {

void register_node_icalls() {
}

} // namespace GDMonoInterop
