// ICall bindings for Node2D
// Auto-generated by glue generator

#include "../../mono_gd/interop/gd_mono_interop_variant.h"

namespace GDMonoInterop {

void register_node2d_icalls() {
}

} // namespace GDMonoInterop
