// AUTO-GENERATED by generate_glue.py - DO NOT EDIT BY HAND.
// Source spec: timer_glue.spec.json
//
// ICall bindings for Timer - generated from a JSON spec.
// All float/double values are passed as integer bit-patterns to comply with
// the WASM Mono interpreter's do_icall signature constraints.

#include "../../mono_gd/interop/gd_mono_interop_variant.h"
#include "../../utils/mono_logger.h"
#include "core/object/class_db.h"
#include "core/string/ustring.h"
#include "scene/main/timer.h"
#include <mono/mono-publib.h>
#include <cstdint>
#include <cstdio>
#include <cstring>

extern "C" {
char *mono_string_to_utf8(MonoString *s);
void mono_free(void *ptr);
}

namespace {

// RAII helper for MonoString -> String conversion.
struct GenMonoStringHolder {
	char *utf8;
	GenMonoStringHolder(MonoString *s) : utf8(s ? mono_string_to_utf8(s) : nullptr) {}
	~GenMonoStringHolder() { if (utf8) mono_free(utf8); }
	bool valid() const { return utf8 != nullptr; }
	String to_string() const { return utf8 ? String::utf8(utf8) : String(); }
};

// Timer::set_wait_time
static void icall_Timer_SetWaitTime(int64_t p_timer, int64_t p_time) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	double p_time_d;
	memcpy(&p_time_d, &p_time, sizeof(double));
	self->set_wait_time(p_time_d);

}

// Timer::get_wait_time
static int64_t icall_Timer_GetWaitTime(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	double _ret_d = (self->get_wait_time());
	int64_t _ret_bits = 0;
	memcpy(&_ret_bits, &_ret_d, sizeof(double));
	return _ret_bits;

}

// Timer::set_one_shot
static void icall_Timer_SetOneShot(int64_t p_timer, mono_bool p_one_shot) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	self->set_one_shot((p_one_shot != 0));

}

// Timer::is_one_shot
static mono_bool icall_Timer_IsOneShot(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	return (mono_bool)(self->is_one_shot());

}

// Timer::set_autostart
static void icall_Timer_SetAutostart(int64_t p_timer, mono_bool p_start) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	self->set_autostart((p_start != 0));

}

// Timer::has_autostart
static mono_bool icall_Timer_HasAutostart(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	return (mono_bool)(self->has_autostart());

}

// Timer::start
static void icall_Timer_Start(int64_t p_timer, int64_t p_time) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	double p_time_d;
	memcpy(&p_time_d, &p_time, sizeof(double));
	self->start(p_time_d);

}

// Timer::stop
static void icall_Timer_Stop(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	self->stop();

}

// Timer::set_paused
static void icall_Timer_SetPaused(int64_t p_timer, mono_bool p_paused) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	self->set_paused((p_paused != 0));

}

// Timer::is_paused
static mono_bool icall_Timer_IsPaused(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	return (mono_bool)(self->is_paused());

}

// Timer::set_ignore_time_scale
static void icall_Timer_SetIgnoreTimeScale(int64_t p_timer, mono_bool p_ignore) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return;
	self->set_ignore_time_scale((p_ignore != 0));

}

// Timer::is_ignoring_time_scale
static mono_bool icall_Timer_IsIgnoringTimeScale(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	return (mono_bool)(self->is_ignoring_time_scale());

}

// Timer::is_stopped
static mono_bool icall_Timer_IsStopped(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	return (mono_bool)(self->is_stopped());

}

// Timer::get_time_left
static int64_t icall_Timer_GetTimeLeft(int64_t p_timer) {
	Timer *self = (Timer *)(intptr_t)p_timer;
	if (!self) return 0;
	double _ret_d = (self->get_time_left());
	int64_t _ret_bits = 0;
	memcpy(&_ret_bits, &_ret_d, sizeof(double));
	return _ret_bits;

}

// ClassDB validation: verify Timer has the methods we bind.
static void scan_and_validate_timer_methods() {
	const char *essential_methods[] = {
		"set_wait_time",
		"get_wait_time",
		"set_one_shot",
		"is_one_shot",
		"set_autostart",
		"has_autostart",
		"start",
		"stop",
		"set_paused",
		"is_paused",
		"set_ignore_time_scale",
		"is_ignoring_time_scale",
		"is_stopped",
		"get_time_left",
		nullptr
	};
	for (int i = 0; essential_methods[i] != nullptr; i++) {
		if (!ClassDB::has_method("Timer", essential_methods[i])) {
			MonoLogger::log_warning(vformat("ClassDB: Timer::%s not found", essential_methods[i]));
		}
	}
}

} // anonymous namespace

namespace GDMonoInterop {

void register_timer_icalls() {
	MonoLogger::log("Registering Timer icalls (generated)...");
	scan_and_validate_timer_methods();

	mono_add_internal_call("Godot.Timer::godot_icall_Timer_SetWaitTime", (const void *)icall_Timer_SetWaitTime);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_GetWaitTime", (const void *)icall_Timer_GetWaitTime);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_SetOneShot", (const void *)icall_Timer_SetOneShot);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_IsOneShot", (const void *)icall_Timer_IsOneShot);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_SetAutostart", (const void *)icall_Timer_SetAutostart);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_HasAutostart", (const void *)icall_Timer_HasAutostart);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_Start", (const void *)icall_Timer_Start);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_Stop", (const void *)icall_Timer_Stop);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_SetPaused", (const void *)icall_Timer_SetPaused);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_IsPaused", (const void *)icall_Timer_IsPaused);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_SetIgnoreTimeScale", (const void *)icall_Timer_SetIgnoreTimeScale);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_IsIgnoringTimeScale", (const void *)icall_Timer_IsIgnoringTimeScale);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_IsStopped", (const void *)icall_Timer_IsStopped);
	mono_add_internal_call("Godot.Timer::godot_icall_Timer_GetTimeLeft", (const void *)icall_Timer_GetTimeLeft);
	MonoLogger::log("Timer icalls registered (14 methods)");
}

} // namespace GDMonoInterop
